name: kami

site:
  favicon: /favicon.svg
  # 开屏图 svg 标签，注意 XSS
  logo_svg: null
  # 随机图片
  figure: null

  # 副标题
  subtitle: null

  background:
    src:
      light: https://pximg.xiaohan-kaka.me/img-original/img/2024/06/15/16/55/14/119658407_p0.jpg
      dark: https://pximg.xiaohan-kaka.me/img-original/img/2024/01/28/17/08/46/115557051_p0.jpg
    position: top center fixed

  header:
    menu:
      - title: 源
        path: /
        type: Home
        icon: faDotCircle
        subMenu: []
      - title: 文
        path: /posts
        type: Post
        subMenu: []
        icon: faGlasses
      - title: 记
        type: Note
        path: /notes/latest
        icon: faFeatherAlt
      - title: 言
        path: /says
        icon: faComments
      - title: 览
        icon: faHistory
        path: /timeline
        subMenu:
          - title: 生活
            icon: faFeatherAlt
            path: /timeline?type=note
          - title: 博文
            icon: faBookOpen
            path: /timeline?type=post
          - title: 回忆
            icon: faCircle
            path: /timeline?memory=1
      - title: 友
        icon: faUserFriends
        path: /friends
      - title: 诉
        icon: faComment
        path: /recently
      - title: 余
        icon: faCircleNotch
        path: /favorite/music
        subMenu:
          - title: 听歌
            icon: faMusic
            type: Music
            path: /favorite/music
          - title: 项目
            icon: faFlask
            path: /projects
      - title: ''
        icon: faSubway
        path: 'https://travellings.link'
  social: 
      - url: 'https://github.com/Dreamkaka'
        title: GitHub
        icon: faGithub
        color: var(--black)
      - url: 'https://twitter.com/Dreamkaka'
        title: twitter
        icon: faTwitter
        color: '#02A4ED'
  

  footer:
    background:
      src:
        dark: ''
        light: /assets/footer.png
      position: top/cover
    home_page: /
    motto:
      content: 醉后不知天在水，满船清梦压星河。
      author: 题龙阳县青草湖
    icp:
      enable: true
      label: '萌备 20231369 号'
      link: https://icp.gov.moe/?keyword=20231369

    navigation:
      - name: 前往主站
        path: https://blog.xiaohan-kaka.me
        newtab: true
      - name: 关于
        path: '/about'
      - name: 留言
        path: '/message'
      - name: 友链
        path: '/friends'
      - name: RSS 订阅
        path: '/feed'
        newtab: true
      - name: 站点地图
        path: '/sitemap'
        newtab: true
      - name: 开往
        path: https://travellings.link/
        newtab: true

  custom:
    script: ''
    style: ''
    js: 
      - https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js
    css: 
      - https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css

page:
  home:
    sections:
      - post
      - note
      - friend
      - more
    title_mapping:
      post: ''
      note: ''
      friend: ''
      more: ''
    more:
      - name: 点赞
        type: 'like'
        cover:
      - name: 订阅
        type: 'subscribe'
        cover:

function:
  comment:
    disable: false
  player:
    # 默认播放列表
    # 只支持网易云
    id:
      - 8101231686
      - 8800929194
      - 1450252250
  analyze:
    enable: true
    ga: ''
    baidu: ''
    umami:
      id: 'df3c8bd0-4a37-4651-9f70-9e115611ce80'
      url: 'https://umami.xiaohan-kaka.me/'
      jsname: 'umami'
      # 这是我魔改版本 umami 专属
      endpoint: 'collect'
      hostUrl: '/'
  donate:
    enable: false
    link: https://afdian.net/@example
    qrcode: []

  ban_devtool:
    enable: false

  notification:     
    welcome:
      title: 欢迎来到晓寒の互联网自留之地-二号站
      message: 若想回到/前往主站，戳我
      icon: https://xiaorunshu.com/android-chrome-192x192.png
      to-link: //blog.xiaohan-kaka.me
